spring:
  application:
    name: "auth"
  devtools:
    add-properties: false
  profiles:
    active: ${PROFILE:dev}
    include: null

management:
  endpoints:
    web:
      base-path: /auth/actuator
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

routes:
  paths:
    users: "/auth/api/v1/users"
    usersById: "/auth/api/v1/users/{id}"
    usersByDocument: "/auth/api/v1/users/byDocument/{document}"
    authLogin: "/auth/api/v1/auth/login"
    rolaHasPermission: "/auth/api/v1/auth/roleHasPermission"

springdoc:
  swagger-ui:
    path: /auth/openapi/swagger-ui
  api-docs:
    path: /auth/openapi/v3/api-docs
  packages-to-scan:
    - co.com.crediya
  paths-to-match:
    - /**





