##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: auth
  devtools:
    add-properties: false
  profiles:
    include: null

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/auth?allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: 1234

