server:
  port: 8080
spring:
  application:
    name: "auth"
  devtools:
    add-properties: false
  profiles:
    include: null

  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  config:
    import: aws-secretsmanager:crediya/auth

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: ${ALLOWED_ORIGINS}

routes:
  paths:
    users: "/api/v1/users"
    usersById: "/api/v1/users/{id}"
    usersByDocument: "/api/v1/users/byDocument/{document}"
    authLogin: "/api/v1/auth/login"
    rolaHasPermission: "/api/v1/auth/roleHasPermission"

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui
  api-docs:
    path: /openapi/v3/api-docs
  packages-to-scan:
    - co.com.crediya
  paths-to-match:
    - /**

security:
  jwt:
    expiration: ${JWT_EXPIRATION}
    public-key-location: ${JWT_PUBLIC_KEY}
    private-key-location: ${JWT_SECRET_KEY}





