server:
  port: 8080
spring:
  application:
    name: "auth"
  devtools:
    add-properties: false
  profiles:
    include: null

  r2dbc:
    url: "r2dbc:mysql://localhost:3306/auth?allowPublicKeyRetrieval=true&useSSL=false"
    username: "user"
    password: 1234

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    users: "/api/v1/users"
    usersById: "/api/v1/users/{id}"


springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/v3/api-docs
  packages-to-scan: co.com.crediya
  paths-to-match: /**


