server:
  servlet:
    context-path: /auth
  port: 8080
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/auth?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: 1234

cors:
  allowed-origins: http://localhost:4200,http://localhost:8080

security:
  jwt:
    expiration: ${JWT_EXPIRATION}
    public-key-location: ${JWT_PUBLIC_KEY}
    private-key-location: ${JWT_SECRET_KEY}