server:
  port: ${PORT}
spring:
  config:
    import: ${AWS_NAME_SECRET_MANAGER}
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

cors:
  allowed-origins: ${ALLOWED_ORIGINS}

security:
  jwt:
    expiration: ${JWT_EXPIRATION}
    public-key-location: ${JWT_PUBLIC_KEY}
    private-key-location: ${JWT_SECRET_KEY}